### ISSUE TITLE
Not getting description for classes and method.

### ISSUE THREAD

**Issue by akshay-zz** [ericpopivker/.NET-Fiddle-Intelligent-Completion#2]
Like if If we have
```
var sb= new StringBuilder();
sb.
```
The suggestion method I'm getting don't contains the description. I have checked the code we are not assigning any description for the methods. Can we have a description for the methods and classes?

**Comment by sergey-litvinov** [comment]
Hey, sorry, but this project isn't supported too much. It uses beta versions of Roslyn that was made around 6 years ago and it was never upgraded.

If you want to make it work, you would need to upgrade that project to the latest Roslyn version, and then implement own https://docs.microsoft.com/dotnet/api/microsoft.codeanalysis.documentationprovider?view=roslyn-dotnet that will parse `SomeProject.xml` file generated by MSBuild and match it to specific classes\methods. We have https://github.com/ericpopivker/.NET-Fiddle-Intelligent-Completion/blob/master/src/DotNetFiddle.IntelligentCompletion/DocumentationProviderFactory.cs  there, but most likely it won't work as it uses internal provider

You can also try to use newer [XmlDocumentationProvider](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Utilities/Documentation/XmlDocumentationProvider.cs ) that Roslyn has and it might work right away, but i can't say for sure

**Comment by akshay-zz** [comment]
Thanks for your valuable comment. I will look into this.
